name: Remove unused images from registry

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  Delete untagged images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all images from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
